### ISSUE TITLE
Service binding and scheduling from 'working' thread

### ISSUE THREAD

**Issue by almozavr** [stanfy/goro#4]
`BoundGoroImpl` uses `onServiceConnected` which is always called in `MainThread` by Android. In the same time, `schedule(...)` could be called from any thread. And in case `bindOneshot` `onServiceConnected` could be called even before `schedule` puts `future` into `postponed` - in this case, future would never start.

Quick ugly fix is here https://github.com/almozavr/goro/commit/76a17c82aa9071775e33ed2d80afd0a7cdd4fdb5 - I think it's no good to be merged into library, but I want to start a discussion.

**Comment by roman-mazur** [comment]
Both `schedule` and `onServiceConnected` bodies are supposed to be synchronized using `lock`... Hence, it's not really obvious for me why this does not work. I will try to reproduce.

**Comment by almozavr** [comment]
Yes, but it doesn't save you, because client calls `bind` (which starts `onServiceConnected` in main thread) and only then calls `schedule`.
Possible api-friendly solution could be `bindOneshot` changes:
```
    @Override
    public <T> ObservableFuture<T> bindOneshot(String queueName, Callable<T> task) {      
      synchronized (lock) {
        oneshot = true;
      }
      ObservableFuture<T> future = schedule(queueName, task);
      GoroService.bind(context, BoundGoroImpl.this);
      return future;     
    }
```

**Comment by almozavr** [comment]
I've tried  ↑ but saw it breaks the flaw of wrapping `BoundGoro` with decorators like `RxGoro`. So it's not the way. Another solution comes to my mind is to delegate unbinding from `onServiceConnected` to some another place or, check if there is no pending jobs scheduled and make double check for unbind from `schedule` call.

**Comment by roman-mazur** [comment]
Ah, now I see the problem... `onServiceConnected` is invoked before `schedule`, and in case of `bindOneshot` we unbind from the service as soon as `onServiceConnected` completes. Hence, `postponed` list is never processed.

I'm thinking about making a separate `Goro` implementation that will bind to the service if `schedule` is invoked and unbind as soon as current work is delegated.
So, in your case, `bindOneShot` will not be called at all (and we'll deprecate this method). Binding will be performed on every `schedule` if it's required.
And there will be 2 implementations for `Goro` that communicates with a service:
- current `BoundGoro` with explicit control allowing to adjust `bind()`/`unbind` with another component lifecycle
- `Goro.oneshot()` without no extra methods beyond `Goro` interface that will do binding on demand and unbind asap.

Opinions?

**Comment by almozavr** [comment]
Sounds good, +1.

**Comment by roman-mazur** [comment]
Although we have a few thing to finish before 3.0 release, version 3.0.0-RC1 will be in Maven Central soon (it's already released, waiting for the sync). Please let me know how it works for you, if you get some time.

**Comment by almozavr** [comment]
@roman-mazur LGTM, thanks!
